select
    id as place_id,
    google_place_id,
    deck_sku,
    name,
    description,
    formatted_address,
    formatted_phone_number,
    website,
    url,
    latitude::numeric as location_lat,
    longitude::numeric as location_lng,
    types,
    categories,
    rating,
    user_ratings_total,
    price_level,
    business_status,
    opening_hours,
    reservable,
    takeout,
    dine_in,
    serves_beer,
    serves_dinner,
    serves_lunch,
    serves_wine,
    serves_brunch,
    serves_vegetarian_food,
    wheelchair_accessible_entrance,
    serves_breakfast,
    is_featured,
    is_spotlight,
    instagram_handles,
    source_type,
    booking_url,
    first_discovered_at,
    last_updated_at,
    created_at,
    updated_at
from {{ source("public", "places") }}